"""
HTML result reporter
"""

import json
from typing import Dict, Any, Optional
from pathlib import Path

from .base import BaseReporter, ReporterType
from processor.base import ProcessedData


class HTMLReporter(BaseReporter):
    """HTML结果展示器"""

    def __init__(self, output_dir: str = "./results"):
        super().__init__(output_dir)

    def get_reporter_type(self) -> ReporterType:
        return ReporterType.HTML

    def report(self, processed_data: ProcessedData, output_file: Optional[str] = None) -> str:
        """生成HTML报告"""
        if output_file is None:
            timestamp = int(processed_data.timestamp)
            output_file = f"perf_report_{timestamp}.html"

        output_path = self._get_output_path(output_file)

        html_content = self._generate_html(processed_data)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)

        return str(output_path)

    def _generate_html(self, processed_data: ProcessedData) -> str:
        """生成HTML内容"""
        data = processed_data.processed_data

        html_template = f"""
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>iSulad Performance Test Report</title>
    <style>
        {self._get_css_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>iSulad Performance Test Report</h1>
            <p class="subtitle">Generated at {processed_data.timestamp:.0f}</p>
        </header>

        <main>
            {self._generate_summary_section(data)}
            {self._generate_test_analysis_section(data)}
            {self._generate_engine_comparison_section(data)}
            {self._generate_insights_section(data)}
        </main>

        <footer class="footer">
            <p>Report generated by iSulad Performance Testing Framework</p>
        </footer>
    </div>

    <script>
        {self._get_javascript()}
    </script>
</body>
</html>
        """

        return html_template

    def _get_css_styles(self) -> str:
        """获取CSS样式"""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            box-shadow: 0 0 20px rgba(0,0,0,0.1);
        }

        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 2rem;
            text-align: center;
        }

        .header h1 {
            font-size: 2.5rem;
            margin-bottom: 0.5rem;
        }

        .subtitle {
            opacity: 0.9;
            font-size: 1.1rem;
        }

        main {
            padding: 2rem;
        }

        .section {
            margin-bottom: 3rem;
            background: white;
            border-radius: 8px;
            padding: 2rem;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }

        .section h2 {
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 0.5rem;
            margin-bottom: 1.5rem;
            font-size: 1.8rem;
        }

        .metric-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 1rem;
            margin-bottom: 2rem;
        }

        .metric-card {
            background: #f8f9fa;
            padding: 1.5rem;
            border-radius: 8px;
            border-left: 4px solid #3498db;
            text-align: center;
        }

        .metric-card h3 {
            color: #2c3e50;
            margin-bottom: 0.5rem;
            font-size: 0.9rem;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .metric-value {
            font-size: 2rem;
            font-weight: bold;
            color: #3498db;
            margin-bottom: 0.25rem;
        }

        .metric-unit {
            color: #7f8c8d;
            font-size: 0.8rem;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 1rem 0;
            background: white;
        }

        th, td {
            padding: 0.75rem;
            text-align: left;
            border-bottom: 1px solid #ecf0f1;
        }

        th {
            background: #f8f9fa;
            font-weight: 600;
            color: #2c3e50;
        }

        tr:hover {
            background: #f8f9fa;
        }

        .status-success {
            color: #27ae60;
            font-weight: bold;
        }

        .status-failure {
            color: #e74c3c;
            font-weight: bold;
        }

        .performance-good {
            color: #27ae60;
        }

        .performance-medium {
            color: #f39c12;
        }

        .performance-poor {
            color: #e74c3c;
        }

        .insights-list {
            list-style: none;
            padding: 0;
        }

        .insights-list li {
            padding: 1rem;
            margin: 0.5rem 0;
            background: #f8f9fa;
            border-radius: 4px;
            border-left: 4px solid #f39c12;
        }

        .bottleneck {
            border-left-color: #e74c3c;
        }

        .recommendation {
            border-left-color: #3498db;
        }

        .footer {
            text-align: center;
            padding: 2rem;
            background: #34495e;
            color: white;
        }

        .chart-container {
            margin: 2rem 0;
            padding: 1rem;
            background: #f8f9fa;
            border-radius: 8px;
            text-align: center;
        }

        .tabs {
            display: flex;
            margin-bottom: 1rem;
            border-bottom: 1px solid #ecf0f1;
        }

        .tab {
            padding: 0.75rem 1.5rem;
            cursor: pointer;
            background: #f8f9fa;
            border: none;
            border-bottom: 2px solid transparent;
            transition: all 0.3s;
        }

        .tab.active {
            background: white;
            border-bottom-color: #3498db;
            color: #3498db;
        }

        .tab-content {
            display: none;
        }

        .tab-content.active {
            display: block;
        }

        @media (max-width: 768px) {
            .container {
                margin: 0;
            }

            .header {
                padding: 1rem;
            }

            .header h1 {
                font-size: 2rem;
            }

            main {
                padding: 1rem;
            }

            .metric-grid {
                grid-template-columns: 1fr;
            }
        }
        """

    def _generate_summary_section(self, data: Dict[str, Any]) -> str:
        """生成摘要部分"""
        if "summary" not in data:
            return ""

        summary = data["summary"]

        metrics_html = ""
        metrics = [
            ("Total Tests", summary.get("total_tests", 0), ""),
            ("Successful Tests", summary.get("successful_tests", 0), ""),
            ("Success Rate", summary.get("success_rate", 0) * 100, "%"),
            ("Total Operations", summary.get("total_operations", 0), ""),
            ("Operation Success Rate", summary.get("operation_success_rate", 0) * 100, "%"),
            ("Total Duration", summary.get("total_duration", 0), "s"),
            ("Avg Test Duration", summary.get("avg_test_duration", 0), "s"),
        ]

        for name, value, unit in metrics:
            if isinstance(value, float):
                if "Duration" in name:
                    value_str = f"{value:.3f}"
                elif "Rate" in name:
                    value_str = f"{value:.1f}"
                else:
                    value_str = f"{value:.2f}"
            else:
                value_str = str(value)

            metrics_html += f"""
            <div class="metric-card">
                <h3>{name}</h3>
                <div class="metric-value">{value_str}</div>
                <div class="metric-unit">{unit}</div>
            </div>
            """

        return f"""
        <section class="section">
            <h2>Overall Summary</h2>
            <div class="metric-grid">
                {metrics_html}
            </div>
        </section>
        """

    def _generate_test_analysis_section(self, data: Dict[str, Any]) -> str:
        """生成测试分析部分"""
        if "test_analysis" not in data:
            return ""

        analysis = data["test_analysis"]

        test_tabs = ""
        test_contents = ""

        for i, (test_name, test_data) in enumerate(analysis.items()):
            active_class = "active" if i == 0 else ""
            test_tabs += f'<button class="tab {active_class}" onclick="showTab({i})">{test_name}</button>'

            if isinstance(test_data, dict) and "error" not in test_data:
                content = self._generate_test_detail_table(test_data)
            else:
                if isinstance(test_data, dict):
                    err_msg = test_data.get("error", "Unknown error")
                else:
                    err_msg = str(test_data)
                content = f"<p>Error: {err_msg}</p>"

            test_contents += f'<div class="tab-content {active_class}" id="tab-{i}">{content}</div>'

        return f"""
        <section class="section">
            <h2>Test Analysis</h2>
            <div class="tabs">
                {test_tabs}
            </div>
            {test_contents}
        </section>
        """

    def _generate_test_detail_table(self, test_data: Dict[str, Any]) -> str:
        """生成测试详情表格"""
        table_html = """
        <table>
            <thead>
                <tr>
                    <th>Metric</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
        """

        metrics = [
            ("Test Count", test_data.get("test_count", 0)),
            ("Total Operations", test_data.get("total_operations", 0)),
            ("Successful Operations", test_data.get("successful_operations", 0)),
            ("Success Rate", f"{test_data.get('success_rate', 0)*100:.1f}%"),
        ]

        if "avg_duration" in test_data:
            metrics.extend([
                ("Average Duration", f"{test_data.get('avg_duration', 0):.6f}s"),
                ("Min Duration", f"{test_data.get('min_duration', 0):.6f}s"),
                ("Max Duration", f"{test_data.get('max_duration', 0):.6f}s"),
                ("Std Deviation", f"{test_data.get('std_duration', 0):.6f}s"),
                ("Median Duration", f"{test_data.get('median_duration', 0):.6f}s"),
                ("95th Percentile", f"{test_data.get('p95_duration', 0):.6f}s"),
                ("99th Percentile", f"{test_data.get('p99_duration', 0):.6f}s"),
                ("Operations/Second", f"{test_data.get('operations_per_second', 0):.2f}"),
            ])

        for name, value in metrics:
            table_html += f"<tr><td>{name}</td><td>{value}</td></tr>"

        table_html += "</tbody></table>"

        # 添加引擎细分
        if "engines" in test_data:
            engine_table = self._generate_engine_table(test_data["engines"])
            table_html += f"<h3>Engine Breakdown</h3>{engine_table}"

        return table_html

    def _generate_engine_table(self, engines: Dict[str, Any]) -> str:
        """生成引擎表格"""
        table_html = """
        <table>
            <thead>
                <tr>
                    <th>Engine</th>
                    <th>Operations</th>
                    <th>Successful</th>
                    <th>Avg Duration</th>
                    <th>Ops/Sec</th>
                </tr>
            </thead>
            <tbody>
        """

        for engine_name, metrics in engines.items():
            table_html += f"""
            <tr>
                <td>{engine_name}</td>
                <td>{metrics.get('operation_count', 0)}</td>
                <td>{metrics.get('successful_count', 0)}</td>
                <td>{metrics.get('avg_duration', 0):.4f}</td>
                <td>{metrics.get('operations_per_second', 0):.2f}</td>
            </tr>
            """

        table_html += "</tbody></table>"
        return table_html

    def _generate_engine_comparison_section(self, data: Dict[str, Any]) -> str:
        """生成引擎对比部分"""
        if "engine_comparison" not in data:
            return ""

        comparison = data["engine_comparison"]

        content = ""
        for test_name, test_comparison in comparison.items():
            if isinstance(test_comparison, dict) and "error" not in test_comparison:
                content += f"<h3>{test_name}</h3>"
                content += self._generate_comparison_table(test_comparison)
            else:
                if isinstance(test_comparison, dict):
                    err_msg = test_comparison.get("error", "Unknown error")
                else:
                    err_msg = str(test_comparison)
                content += f"<h3>{test_name}</h3><p>Error: {err_msg}</p>"

        return f"""
        <section class="section">
            <h2>Engine Comparison</h2>
            {content}
        </section>
        """

    def _generate_comparison_table(self, test_comparison: Dict[str, Any]) -> str:
        """生成对比表格"""
        table_html = """
        <table>
            <thead>
                <tr>
                    <th>Engine</th>
                    <th>Avg Duration</th>
                    <th>Ops/Sec</th>
                    <th>Success Rate</th>
                    <th>Relative Performance</th>
                </tr>
            </thead>
            <tbody>
        """

        baseline_engine = test_comparison.get("baseline_engine")
        relative_perf = test_comparison.get("relative_performance", {})

        for engine_name, metrics in test_comparison.get("engine_metrics", {}).items():
            relative = relative_perf.get(engine_name, {})
            perf_value = relative.get("performance_ratio", 1.0)
            is_faster = relative.get("is_faster", False)

            perf_class = "performance-good" if is_faster else "performance-medium"
            baseline_mark = " (baseline)" if engine_name == baseline_engine else ""

            table_html += f"""
            <tr>
                <td>{engine_name}{baseline_mark}</td>
                <td>{metrics.get('avg_duration', 0):.4f}</td>
                <td>{metrics.get('operations_per_second', 0):.2f}</td>
                <td>{metrics.get('success_rate', 0)*100:.1f}%</td>
                <td class="{perf_class}">{perf_value:.2f}x</td>
            </tr>
            """

        table_html += "</tbody></table>"
        return table_html

    def _generate_insights_section(self, data: Dict[str, Any]) -> str:
        """生成洞察部分"""
        if "performance_insights" not in data:
            return ""

        insights = data["performance_insights"]

        content = ""

        # 瓶颈
        if insights.get("bottlenecks"):
            bottleneck_items = ""
            for bottleneck in insights["bottlenecks"]:
                bottleneck_items += f"""
                <li class="bottleneck">
                    <strong>{bottleneck['test']}</strong> on {bottleneck['engine']}:
                    Average duration {bottleneck['avg_duration']:.3f}s (Severity: {bottleneck['severity']})
                </li>
                """

            content += f"""
            <h3>Performance Bottlenecks</h3>
            <ul class="insights-list">
                {bottleneck_items}
            </ul>
            """

        # 建议
        if insights.get("recommendations"):
            recommendation_items = ""
            for rec in insights["recommendations"]:
                recommendation_items += f'<li class="recommendation">{rec}</li>'

            content += f"""
            <h3>Recommendations</h3>
            <ul class="insights-list">
                {recommendation_items}
            </ul>
            """

        # 趋势
        if insights.get("trends"):
            trend_items = ""
            for trend in insights["trends"]:
                trend_items += f'<li>{trend["description"]}</li>'

            content += f"""
            <h3>Performance Trends</h3>
            <ul class="insights-list">
                {trend_items}
            </ul>
            """

        # 异常
        if "anomalies" in data and data["anomalies"]:
            anomaly_items = ""
            for anomaly in data["anomalies"][:5]:  # 最多显示5个异常
                anomaly_items += f"""
                <li>
                    <strong>{anomaly['type']}</strong> in {anomaly['test']} on {anomaly['engine']}:
                    Duration {anomaly['duration']:.4f}s ({anomaly['deviation_sigma']:.1f}σ from mean)
                </li>
                """

            content += f"""
            <h3>Detected Anomalies</h3>
            <ul class="insights-list">
                {anomaly_items}
            </ul>
            """

        return f"""
        <section class="section">
            <h2>Performance Insights</h2>
            {content}
        </section>
        """

    def _get_javascript(self) -> str:
        """获取JavaScript代码"""
        return """
        function showTab(tabIndex) {
            // 隐藏所有标签内容
            const contents = document.querySelectorAll('.tab-content');
            contents.forEach(content => content.classList.remove('active'));

            // 移除所有标签的激活状态
            const tabs = document.querySelectorAll('.tab');
            tabs.forEach(tab => tab.classList.remove('active'));

            // 显示选中的标签内容
            document.getElementById(`tab-${tabIndex}`).classList.add('active');
            tabs[tabIndex].classList.add('active');
        }
        """

